// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPwEmZBXwBWiWQh1oDUx3mbdCm8id8FQ',
    appId: '1:797097519489:web:6a26d190af0ff2431d2080',
    messagingSenderId: '797097519489',
    projectId: 'scentia-edu',
    authDomain: 'scentia-edu.firebaseapp.com',
    storageBucket: 'scentia-edu.firebasestorage.app',
    measurementId: 'G-P88J3XVDGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamf8K8qzDj2Ll8TSlwrprwmmrGM4w5dw',
    appId: '1:797097519489:android:6e7acb5148cb13251d2080',
    messagingSenderId: '797097519489',
    projectId: 'scentia-edu',
    storageBucket: 'scentia-edu.firebasestorage.app',
  );
}
